[versions]
agp="8.7.3"
kotlin="2.0.21"
composeBom="2024.12.01"
core="1.15.0"
activity="1.10.0"
lifecycle="2.8.7"
coroutines="1.9.0"
hilt="2.53.1"
hiltNav="1.2.0"
room="2.6.1"
work="2.10.0"
serialization="1.7.3"

[libraries]
androidx-core={module="androidx.core:core-ktx",version.ref="core"}
activity-compose={module="androidx.activity:activity-compose",version.ref="activity"}
compose-bom={module="androidx.compose:compose-bom",version.ref="composeBom"}
compose-ui={module="androidx.compose.ui:ui"}
compose-preview={module="androidx.compose.ui:ui-tooling-preview"}
compose-tooling={module="androidx.compose.ui:ui-tooling"}
material3={module="androidx.compose.material3:material3"}
icons={module="androidx.compose.material:material-icons-extended"}
lifecycle-runtime={module="androidx.lifecycle:lifecycle-runtime-ktx",version.ref="lifecycle"}
lifecycle-compose={module="androidx.lifecycle:lifecycle-runtime-compose",version.ref="lifecycle"}
viewmodel-compose={module="androidx.lifecycle:lifecycle-viewmodel-compose",version.ref="lifecycle"}
coroutines-android={module="org.jetbrains.kotlinx:kotlinx-coroutines-android",version.ref="coroutines"}
serialization-json={module="org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref="serialization"}
hilt-android={module="com.google.dagger:hilt-android",version.ref="hilt"}
hilt-compiler={module="com.google.dagger:hilt-android-compiler",version.ref="hilt"}
hilt-navigation={module="androidx.hilt:hilt-navigation-compose",version.ref="hiltNav"}
room-runtime={module="androidx.room:room-runtime",version.ref="room"}
room-ktx={module="androidx.room:room-ktx",version.ref="room"}
room-compiler={module="androidx.room:room-compiler",version.ref="room"}
work-runtime={module="androidx.work:work-runtime-ktx",version.ref="work"}
hilt-work={module="androidx.hilt:hilt-work",version.ref="hiltNav"}

[plugins]
android-application={id="com.android.application",version.ref="agp"}
android-library={id="com.android.library",version.ref="agp"}
kotlin-android={id="org.jetbrains.kotlin.android",version.ref="kotlin"}
kotlin-compose={id="org.jetbrains.kotlin.plugin.compose",version.ref="kotlin"}
ksp={id="com.google.devtools.ksp",version="2.0.21-1.0.28"}
hilt={id="com.google.dagger.hilt.android",version.ref="hilt"}
